In [ ]:
import numpy as np

List vs Numpy-Time taken

In [ ]:
from time import process_time

Time taken by list

In [ ]:
python_list=[i for i in range(10000)]

start_time = process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time - start_time)

0.001383084000000423


Time taken by numpy array

In [ ]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00020487200000118833


Numpy array

In [ ]:
#List
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating 1-D array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
#2-D array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
type(b)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy array

In [ ]:
#array of zero values
a=np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#array of ones
b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#array of particular value
c=np.full((4,6),5)
print(c)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [ ]:
#create an identity matrix
a =np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create numpy array with random values
r=np.random.random((3,4))
print(r)


[[0.60221351 0.67548329 0.78491049 0.59578064]
 [0.94825171 0.90349387 0.37665954 0.24512331]
 [0.88391185 0.14131873 0.04515332 0.35427619]]


In [ ]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[93 20 45 65 82]
 [44 49 53 76 74]
 [16 83 25 48 15]]


In [ ]:
#array of evenly spaced values-->specifying the number of values required
d=np.linspace(10,30,3)
print(d)

[10. 20. 30.]


In [ ]:
#array of evenly spaced values-->specifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert a list to a numpy array
list2=[1,2,3,4,5]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


numpy.ndarray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[79 44 27 40 14]
 [86 60 40 31 53]
 [57 72 20 82 84]
 [14 21 28 83 61]
 [23 68 50 27 59]]


In [ ]:
#array dimension
c.shape

(5, 5)

In [ ]:
#number of dimensions
c.ndim

2

In [ ]:
#number of elements in an array
c.size

25

In [ ]:
#checking the datatype of the values in the array
print(c.dtype)

int64


**Mathematical operations on a np array**

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2)  #comcatinate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

print(a)
print(b)


[[3 1 8]
 [7 5 9]
 [7 8 7]]
[[12 13 12]
 [16 10 15]
 [15 11 18]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 14 20]
 [23 15 24]
 [22 19 25]]
[[ -9 -12  -4]
 [ -9  -5  -6]
 [ -8  -3 -11]]
[[ 36  13  96]
 [112  50 135]
 [105  88 126]]
[[0.25       0.07692308 0.66666667]
 [0.4375     0.5        0.6       ]
 [0.46666667 0.72727273 0.38888889]]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

print(a)
print(b)


[[9 2 6]
 [2 0 7]
 [9 9 4]]
[[14 16 19]
 [13 15 15]
 [11 10 19]]


In [ ]:
print(np.add(a,b))

[[23 18 25]
 [15 15 22]
 [20 19 23]]


In [ ]:
print(np.subtract(a,b))

[[ -5 -14 -13]
 [-11 -15  -8]
 [ -2  -1 -15]]


In [ ]:
print(np.multiply(a,b))

[[126  32 114]
 [ 26   0 105]
 [ 99  90  76]]


**Array Manipulation**

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 0 5]
 [6 5 2]]
(2, 3)


In [ ]:
#transpose
trans=np.transpose(array)

print(trans)
print(trans.shape)

[[4 6]
 [0 5]
 [5 2]]
(3, 2)


In [ ]:
array=np.random.randint(0,10,(2,4))
print(array)
print(array.shape)

[[0 2 3 5]
 [7 1 8 9]]
(2, 4)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[0 7]
 [2 1]
 [3 8]
 [5 9]]
(4, 2)


In [ ]:
#reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 1 0]
 [2 6 5]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)
(b.shape)

[[2 1]
 [0 2]
 [6 5]]


(3, 2)